title:            Corsino
description:      Personal Blog

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://bmcorsino.github.io 


# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  #- title: 'Favorites'
   # url: '#'
    #submenu:
     # - title: 'Code Highlighter'
      #  url: '/intro/code-highlighting-post/'
      #- title: 'Sample Post'
      #  url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Corsino
  site:           bmcorsino.github.io
  avatar:         images/avatar.jpg
  bio:            "Azure Active Directory Lover!"
  email:          you@email.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: brunomcorsino # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: bmcorsino

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: brunomcorsino

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/bmcorsino"


# Career variables

events:

  - image: "/img/career/finch.png"
    date: "February 2017 - July 2017"
    description: "Data Scientist at Finch. Working with Deep Learning and NLP"
  - image: "/img/career/gsoc_2016.jpg"
    date: "March 2016 - August 2016"
    description: "Wow! I'm at Google Summer of Code!! Worked with Python Foundation with Scrapy Streaming project"
  - image: "/img/career/saci.jpg"
    date: "February 2016 - November 2017"
    description: "I'm the coordinator of Saci Lab Unesp (Adaptive Systems and Computational Intelligence Laboratory), a lab about Artificial Intelligence and its applications."
  - image: "/img/career/gsoc_2015.jpg"
    date: "March 2015 - August 2015"
    description: "Wow! I'm at Google Summer of Code!! Worked with Python Foundation with Kivy Designer"
  - image: "/img/career/finch.png"
    date: "April 2015 - October 2015"
    description: "R&D at Finch Soluções, working with NLP and Java."
  - image: "/img/career/unesp.jpg"
    date: "April 2015 - Until now"
    description: "Bachelor of Computer Science at São Paulo State University :)"
  - image: "/img/career/triata.jpg"
    date: "September 2013 - January 2015"
    description: "R&D, focusing on Mobile and Web solutions."
  - image: "/img/career/cti.jpg"
    date: "February 2012 - December 2014"
    description: "Started to study Computer Programming at CTI - Unesp/Bauru."    

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Lisbon
locale:      pt_PT
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
